/**
 * Named aliases over the generated Partner Storefront API types, plus the success shapes
 * (the generated response types mix success and error fields; these are the success halves).
 *
 * Project: zorasocial — Zora Agent Lab on the Groupon Partner Storefront API
 * Module:  src/contracts/partner.ts
 * Deps:    src/contracts/partner.gen.ts (generated by `bun run gen:contracts`, never edited by hand)
 * Tested:  n/a (types only)
 */
import type { components } from "./partner.gen";

type S = components["schemas"];

export type OctoProduct = S["OctoProduct"];
export type OctoOption = S["OctoOption"];
export type OctoUnit = S["OctoUnit"];
export type OctoPricing = S["OctoPricing"];
export type OctoDiscountedPrice = S["OctoDiscountedPrice"];
export type OctoLocation = S["OctoLocation"];
export type OctoMedia = S["OctoMedia"];
export type OctoCart = S["OctoCart"];
export type OctoCartItem = S["OctoCartItem"];
export type OctoCartTotals = S["OctoCartTotals"];
export type OctoCartMessage = S["OctoCartMessage"];
export type OctoCartStatus = S["OctoCartStatus"];
export type OctoBookingStatus = S["OctoBookingStatus"];
export type OctoErrorCode = S["OctoErrorCode"];
export type OctoProductStatus = S["OctoProductStatus"];
export type CartItemInput = S["CartItemInput"];
export type PartnerBookingItem = S["PartnerBookingItem"];
export type PartnerBookingUnitItem = S["PartnerBookingUnitItem"];
export type PartnerRegistrationInput = S["PartnerRegistrationInput"];

/** One page of the catalogue, success half of ProductsListResponse. */
export interface ProductsPage {
  readonly products: readonly OctoProduct[];
  readonly hasMore: boolean;
  readonly nextCursor: string | null;
  /** Server time of this page. The final page's value minus 10 minutes is the next watermark. */
  readonly timestamp: string;
}

/** Success half of PartnerMeGetResponse. Never carries the API key. */
export interface PartnerRegistration {
  readonly partnerId: string;
  readonly displayName: string;
  readonly status: S["PartnerStatus"];
  readonly partnerContactName: string;
  readonly partnerContactEmail: string;
  readonly inventoryCountries: readonly string[];
  readonly inventoryStates: readonly string[];
  readonly category0: readonly string[];
  readonly category1: readonly string[];
  readonly category2: readonly string[];
  readonly cjPublisherId: string | null;
  readonly logoUrl: string | null;
  readonly redirectUrl: string | null;
  readonly maxPageSize: number | null;
  readonly createdAt: string;
  readonly updatedAt: string;
}

/** Success half of SupplierGetResponse. */
export interface Supplier {
  readonly id: string;
  readonly name: string;
  readonly endpoint: string;
}

/** Success half of PartnerBookingGetResponse. */
export interface Booking {
  readonly uuid: string;
  readonly id: string;
  readonly status: OctoBookingStatus;
  readonly utcCreatedAt: string;
  readonly items: readonly PartnerBookingItem[];
}

/** Query for GET /products. `country` is always US and is added by the client. */
export interface ProductsQuery {
  readonly limit?: number;
  readonly cursor?: string;
  readonly state?: string;
  readonly category0?: string;
  readonly category1?: string;
  readonly category2?: string;
  /** Never send on a delta (guide, Syncing the catalog). */
  readonly active?: boolean;
  readonly updatedSince?: string;
}

/** Booking statuses that mean "keep polling". */
export const PENDING_BOOKING_STATUSES: readonly OctoBookingStatus[] = ["ON_HOLD", "PENDING"];
