/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/octo-gateway/v1/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a cart, together with its first item or items.
         * @description There is no empty cart -- `items` is required and must hold at least one
         *     entry. All items are validated before anything is added: if any one fails,
         *     nothing is added and no cart is created.
         *
         *     Returns the full cart, including the `buyLink` you must use verbatim as your
         *     checkout URL. Store the returned cart `id` against the shopper's session on
         *     your server and treat it as a secret -- anyone holding it can change the cart.
         *
         *     Send `expectedPrice` per item: the per-unit price your site is showing. If
         *     Groupon's live price differs the call fails with `PRICE_MISMATCH` and reports
         *     the current price, so you can update your side and ask the shopper to confirm
         *     before retrying. Without it, the shopper may see one price on your site and
         *     another at checkout.
         *
         *     Limits: at most 20 different options per cart, and quantity 1 to 100 per line.
         */
        post: operations["cartsCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/octo-gateway/v1/carts/{cartId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a cart: its items, totals and current `buyLink`.
         * @description Always read the `buyLink` from the most recent cart response rather than
         *     storing one -- it is refreshed on every call.
         *
         *     A `cartId` that was not created by your partner account returns `INVALID_CART_ID`.
         */
        get: operations["cartsGet"];
        put?: never;
        post?: never;
        /**
         * Abandon a cart. Returns no body on success.
         * @description Call this when the shopper empties their basket or leaves, and discard the
         *     `cartId` afterwards. Also discard it once an order has been placed from it.
         *
         *     After abandoning, reading the cart or removing an item returns `404`. Adding
         *     or updating an item does not fail -- it starts a fresh cart under the same
         *     id -- so stop using the id rather than relying on an error.
         *
         *     A `cartId` that was not created by your partner account returns `INVALID_CART_ID`.
         */
        delete: operations["cartsAbandon"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/octo-gateway/v1/carts/{cartId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add one or more items to an existing cart.
         * @description This ADDS quantity rather than replacing it, so a retry after a timeout can
         *     double a line. On a timeout, read the cart back and reconcile instead of
         *     blind-retrying. Adding an option the cart already holds increases that line's
         *     quantity rather than creating a second line.
         *
         *     Returns the full updated cart, including a fresh `buyLink`.
         *
         *     Limits: at most 20 different options per cart, and quantity 1 to 100 per line.
         *
         *     A `cartId` that was not created by your partner account returns `INVALID_CART_ID`.
         */
        post: operations["cartItemsAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/octo-gateway/v1/carts/{cartId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove one item from a cart.
         * @description `itemId` is the cart line's `id`, which is the `optionId` the line was
         *     created from. Returns the full updated cart; removing the last line leaves a
         *     cart with `itemCount: 0` rather than deleting it.
         *
         *     A `cartId` that was not created by your partner account returns `INVALID_CART_ID`.
         */
        delete: operations["cartItemsRemove"];
        options?: never;
        head?: never;
        /**
         * Change the quantity of one cart item.
         * @description The quantity you send REPLACES the line's quantity (unlike adding an item,
         *     which increases it). Valid range is 1 to 100; to remove a line, use the
         *     remove-item endpoint rather than setting the quantity to zero.
         *
         *     Returns the full updated cart, including a fresh `buyLink`.
         *
         *     A `cartId` that was not created by your partner account returns `INVALID_CART_ID`.
         */
        patch: operations["cartItemsUpdate"];
        trace?: never;
    };
    "/octo-gateway/v1/partner-bookings/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read an order after checkout, by the `grouponOrderUuid` Groupon appends to your redirect URL.
         * @description Gives the order's status and, under `items`, every product and option that
         *     was bought with one "View on Groupon" link per ticket, so you can confirm the
         *     purchase, match each item to the cart line you sent, and show the shopper
         *     their vouchers.
         *
         *     Poll this after the shopper returns from checkout. An order may briefly
         *     report as pending before payment settles.
         */
        get: operations["partnerBookingGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/octo-gateway/v1/partners/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read your own partner registration: what you registered and what you may sell.
         * @description Use it to check that your API key works. The response never includes the key.
         *     To change anything shown here, contact Groupon support.
         */
        get: operations["partnerMeGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/octo-gateway/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Groupon deals available to you, as OCTO Products.
         * @description Walk the full catalogue once, then poll for changes with `updatedSince`.
         *     Paginate by sending the returned `nextCursor` back as `cursor`, keeping every
         *     other query parameter identical across one walk. `timestamp` is present only
         *     on the last page (`hasMore: false`); use it as the next walk's `updatedSince`.
         *
         *     Deals that require a booking are not returned by this endpoint.
         *
         *     Only the `US` market is available today, so `country=US` is required.
         */
        get: operations["productsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/octo-gateway/v1/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register as a partner and receive your API key.
         * @description This is the only endpoint called without `g-api-key`. The response carries your
         *     registration and your API key as `token`. The key is returned once, in this
         *     response only: store it server-side before doing anything else. Send it as
         *     `g-api-key` on every other request, starting with `GET /octo-gateway/v1/partners/me`
         *     to check it.
         *
         *     While self-registration is closed, every call fails with `error: "SELF_REGISTRATION_CLOSED"`.
         *
         *     A lost or leaked key, and any change to what you registered, goes through Groupon support.
         *
         *     Calls are rate-limited per client IP and in total, and calls that fail validation count toward the
         *     limit, so check your fields before calling. Over the limit the response is HTTP 429 with
         *     `error: "RATE_LIMITED"`; wait for the `retry-after` header before trying again.
         */
        post: operations["partnerRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/octo-gateway/v1/supplier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your supplier record.
         * @description Identifies the Groupon entity your bookings are made against. Read it once at
         *     onboarding to confirm your integration is pointed at the right supplier; it
         *     does not change between requests.
         */
        get: operations["supplierGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/octo/v1/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deprecated alias of `POST /octo-gateway/v1/carts`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         * @deprecated
         * @description Deprecated alias of `POST /octo-gateway/v1/carts`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         */
        post: operations["cartsCreateLegacyPath"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/octo/v1/carts/{cartId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deprecated alias of `GET /octo-gateway/v1/carts/:cartId`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         * @deprecated
         * @description Deprecated alias of `GET /octo-gateway/v1/carts/:cartId`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         */
        get: operations["cartsGetLegacyPath"];
        put?: never;
        post?: never;
        /**
         * Deprecated alias of `DELETE /octo-gateway/v1/carts/:cartId`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         * @deprecated
         * @description Deprecated alias of `DELETE /octo-gateway/v1/carts/:cartId`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         */
        delete: operations["cartsAbandonLegacyPath"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/octo/v1/carts/{cartId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deprecated alias of `POST /octo-gateway/v1/carts/:cartId/items`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         * @deprecated
         * @description Deprecated alias of `POST /octo-gateway/v1/carts/:cartId/items`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         */
        post: operations["cartItemsAddLegacyPath"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/octo/v1/carts/{cartId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deprecated alias of `DELETE /octo-gateway/v1/carts/:cartId/items/:itemId`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         * @deprecated
         * @description Deprecated alias of `DELETE /octo-gateway/v1/carts/:cartId/items/:itemId`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         */
        delete: operations["cartItemsRemoveLegacyPath"];
        options?: never;
        head?: never;
        /**
         * Deprecated alias of `PATCH /octo-gateway/v1/carts/:cartId/items/:itemId`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         * @deprecated
         * @description Deprecated alias of `PATCH /octo-gateway/v1/carts/:cartId/items/:itemId`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         */
        patch: operations["cartItemsUpdateLegacyPath"];
        trace?: never;
    };
    "/octo/v1/partner-bookings/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deprecated alias of `GET /octo-gateway/v1/partner-bookings/:uuid`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         * @deprecated
         * @description Deprecated alias of `GET /octo-gateway/v1/partner-bookings/:uuid`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         */
        get: operations["partnerBookingGetLegacyPath"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/octo/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deprecated alias of `GET /octo-gateway/v1/products`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         * @deprecated
         * @description Deprecated alias of `GET /octo-gateway/v1/products`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         */
        get: operations["productsListLegacyPath"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/octo/v1/supplier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deprecated alias of `GET /octo-gateway/v1/supplier`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         * @deprecated
         * @description Deprecated alias of `GET /octo-gateway/v1/supplier`, kept for integrations built before the rename. Identical request, response and authentication. Removed on 2027-03-31; move to the new path before then.
         */
        get: operations["supplierGetLegacyPath"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Add one or more items to a cart. `items` has the same shape as when creating the cart; an item for an option already in the cart increases that line's quantity instead of adding a second line. */
        AddCartItemsRequest: {
            /** @description ISO-3166 alpha-2 country code. Use `US` -- the only market available today. */
            country?: string;
            items: components["schemas"]["CartItemInput"][];
        };
        /** @description Returned with HTTP 401 when the API key is missing or invalid, before the request reaches the endpoint. */
        AuthenticationError: {
            /** @description Machine-readable failure class, for example invalid_argument, not_found or unauthenticated. */
            code: string;
            /** @description Always `null` on an authentication failure. */
            details?: Record<string, never> | null;
            /** @description Human-readable explanation. Do not branch on it. */
            message: string;
        };
        /** @description One requested line item on a create/add-items request. */
        CartItemInput: {
            /** @description The per-unit price your site is showing, in minor units. When it disagrees with Groupon's live price the call fails with `PRICE_MISMATCH` and reports the current price, so the shopper never sees one price on your site and another at checkout. Optional, but strongly recommended. */
            expectedPrice?: number;
            optionId: string;
            productId: string;
            quantity: number;
        };
        /** @description Create a cart with its first item or items. At least one item is required. */
        CreateCartRequest: {
            clientReference?: string;
            /** @description ISO-3166 alpha-2 country code. Use `US` -- the only market available today. */
            country: string;
            currency?: string;
            items: components["schemas"]["CartItemInput"][];
        };
        /** @enum {string} */
        OctoAvailabilityType: "START_TIME" | "OPENING_HOURS";
        /**
         * @description The lifecycle state of a booking.
         *
         *     | Value | Meaning |
         *     |---|---|
         *     | `ON_HOLD` | Reserved, and either no payment has been taken yet, or payment was taken but the tickets' state could not be read yet. Read the order again later. |
         *     | `PENDING` | Payment is being processed, or it has been taken and the tickets are still being issued. Read the order again later. |
         *     | `CONFIRMED` | Paid and reserved. The shopper's vouchers are available. |
         *     | `REDEEMED` | The shopper has used the booking. |
         *     | `CANCELLED` | Cancelled. The cancel response also carries a `cancellation` block giving the reason. |
         *     | `REJECTED` | The hold was taken but payment could not be captured. Not redeemable, and it will not become redeemable. |
         *     | `EXPIRED` | The hold lapsed before payment. |
         * @enum {string}
         */
        OctoBookingStatus: "ON_HOLD" | "CONFIRMED" | "REDEEMED" | "CANCELLED" | "EXPIRED" | "REJECTED" | "PENDING";
        /** @description A cart. Keep the `id` from the create response and send it as `cartId` on every later call about this cart. */
        OctoCart: {
            /**
             * @description The checkout URL for this cart. Send the shopper here to pay. Always present.
             *
             *     - **With CJ** (a CJ publisher id is registered for your API key): an affiliate
             *     link that credits your CJ account with the sale.
             *     - **Without CJ** (no CJ publisher id is registered for your API key): the direct
             *     Groupon checkout page for the cart. No affiliate attribution applies.
             *
             *     The checkout page itself is cobranded with your display name and logo when a
             *     logo URL is registered for your API key, and the standard Groupon checkout when
             *     it is not.
             *
             *     In both cases take it from the most recent cart response and use it unchanged --
             *     it is rebuilt on every call, and a hand-constructed URL earns no commission.
             */
            buyLink: string;
            clientReference: string | null;
            /** @description ISO-3166 alpha-2 country code. Use `US` -- the only market available today. */
            country: string;
            currency: string;
            id: string;
            itemCount: number;
            items: components["schemas"]["OctoCartItem"][];
            messages: components["schemas"]["OctoCartMessage"][];
            partner: components["schemas"]["OctoCartPartner"];
            status: components["schemas"]["OctoCartStatus"];
            testMode: boolean;
            totals: components["schemas"]["OctoCartTotals"];
            utcCreatedAt: string | null;
            utcExpiresAt: string | null;
            utcUpdatedAt: string | null;
        };
        /**
         * @description One line on a cart.
         *
         *     `productId` and `optionId` are the catalog ids used both to add a line and to
         *     look one up; `id` is the line's own identifier and carries the same value as
         *     `optionId`.
         *
         *     `title`, `optionTitle`, `media` and `pricing` are read live from the catalogue
         *     on every request. When a deal is sold out, has ended, or the option no longer
         *     exists, `available` is `false`, `unavailableReason` says which, and those
         *     fields come back `null` or empty -- the rest of the cart still reads normally.
         */
        OctoCartItem: {
            available: boolean;
            height: number | null;
            id: string;
            /** @description `pricing.retail * quantity`, or `null` when `pricing` is `null` (degraded line -- excluded from `totals`, not treated as $0). */
            lineTotal: number | null;
            media: Record<string, never>;
            optionId: string;
            optionTitle: string | null;
            pricing: components["schemas"]["OctoCartItemPricing"] | null;
            productId: string;
            quantity: number;
            role: string;
            title: string | null;
            unavailableReason: components["schemas"]["OctoCartItemUnavailableReason"];
            url: string;
            width: number | null;
        };
        /**
         * @description What one cart line costs.
         *
         *     `null` on a line whose price could not be read; `messages[]` says why.
         */
        OctoCartItemPricing: {
            currency: string;
            currencyPrecision: number;
            /**
             * @description Tax already included in `retail`, itemised.
             *
             *     Empty when Groupon publishes no per-line tax breakdown for this deal.
             */
            includedTaxes: components["schemas"]["OctoTax"][];
            net: number | null;
            original: number;
            retail: number;
        };
        /**
         * @description Why a cart line cannot be bought, or `null` when it is available.
         * @enum {string|null}
         */
        OctoCartItemUnavailableReason: "SOLD_OUT" | "DEAL_ENDED" | "OPTION_REMOVED" | null;
        /**
         * @description A non-fatal advisory about one cart line.
         *
         *     Read these alongside the cart: a line can be present but not fully priced, and
         *     the message says why. They never mean the request failed.
         */
        OctoCartMessage: {
            code: string;
            content: string;
            /** @description JSONPath into the cart response, e.g. `$.items[0]`. */
            path: string;
            /** @enum {string} */
            type: "warning" | "info";
        };
        /** @description The partner the cart belongs to -- you. */
        OctoCartPartner: {
            /** @description Your display name, as shown to shoppers on Groupon's checkout page. */
            name: string | null;
            /** @description Your partner id: the stable identifier stamped on orders placed from this cart. It does not change when your API key is rotated. */
            partnerId: string;
        };
        /**
         * @description The cart's lifecycle state.
         * @enum {string}
         */
        OctoCartStatus: "ACTIVE" | "LOCKED" | "CHECKED_OUT" | "EXPIRED" | "ABANDONED";
        /**
         * @description Cart totals, in minor units.
         *
         *     A line whose price could not be read contributes nothing here; `messages[]`
         *     says which, so a total is never silently short.
         */
        OctoCartTotals: {
            currency: string;
            currencyPrecision: number;
            grandTotal: number;
            savings: number;
            subtotal: number;
        };
        /** @enum {string} */
        OctoContactField: "firstName" | "lastName" | "emailAddress" | "phoneNumber" | "country" | "notes";
        /** @enum {string} */
        OctoDeliveryFormat: "PDF_URL" | "QRCODE";
        /** @enum {string} */
        OctoDeliveryMethod: "TICKET" | "VOUCHER";
        /**
         * @description A promotional price for one option, and what a shopper needs to use it.
         *
         *     All three fields travel together, and the whole object is `null` when no
         *     promotion applies.
         *
         *     A Groupon extension -- not part of the standard OCTO contract.
         */
        OctoDiscountedPrice: {
            /** @description The promotional price, in the same minor units and currency as the sibling `retail`. */
            amount: number;
            /** @description When the promotion stops working -- ISO-8601 with an explicit UTC offset, e.g. `"2026-04-02T23:59:00+02:00"`. `null` when no end date is known. */
            endDate: string | null;
            /** @description The code a shopper enters to get `amount`, e.g. `"PRIMAVERA"`. `null` when the promotion has no code. */
            promoCode: string | null;
        };
        /** @enum {string} */
        OctoDurationUnit: "hour" | "minute" | "day";
        /** @description The error every failed request reports. Branch on `error`, never on `errorMessage`. The five price fields are present only when `error` is `PRICE_MISMATCH`. */
        OctoError: {
            /** @description `PRICE_MISMATCH` only: ISO-4217 currency of both prices. */
            currency?: string;
            /** @description `PRICE_MISMATCH` only: decimal places to divide by for display. */
            currencyPrecision?: number;
            /** @description `PRICE_MISMATCH` only: the current price, in minor units. Re-render with it and retry in one round-trip. */
            currentPrice?: number;
            error: components["schemas"]["OctoErrorCode"];
            /** @description Human-readable explanation, for your logs. Do not branch on it. */
            errorMessage: string;
            /** @description `PRICE_MISMATCH` only: the price you sent, in minor units. */
            expectedPrice?: number;
            /** @description `PRICE_MISMATCH` only: JSONPath into your request naming the item concerned, e.g. `$.items[0]` or `$.expectedPrice`. */
            path?: string;
            /** @description Quote it when contacting Groupon about the failure. */
            requestId: string;
        };
        /**
         * @description The machine-readable error code returned on a failed request.
         *
         *     Every error response carries one of these as `error`, alongside a
         *     human-readable `errorMessage`. Branch on the code, not the message.
         * @enum {string}
         */
        OctoErrorCode: "INVALID_PRODUCT_ID" | "INVALID_BOOKING_UUID" | "INVALID_CART_ID" | "BAD_REQUEST" | "UNAUTHORIZED" | "FORBIDDEN" | "INVALID_BOOKING_STATE" | "UNPROCESSABLE_ENTITY" | "PRICE_MISMATCH" | "PRODUCT_NOT_CARTABLE" | "CART_ITEM_LIMIT" | "RATE_LIMITED" | "SELF_REGISTRATION_CLOSED" | "INTERNAL_SERVER_ERROR";
        /** @description Returned on every failure other than authentication. The HTTP status matches `code`. */
        OctoErrorEnvelope: {
            /** @description Machine-readable failure class, for example invalid_argument, not_found or unauthenticated. */
            code: string;
            details?: components["schemas"]["OctoError"] | null;
            /** @description Human-readable explanation. Do not branch on it. */
            message: string;
        };
        /** @description Content capability — geographic redemption location. */
        OctoLocation: {
            city: string | null;
            country: string | null;
            id: string | null;
            latitude: number | null;
            longitude: number | null;
            name: string | null;
            postalCode: string | null;
            /** @description Two-letter state or region code, e.g. `NV`. The `state` filter on `GET /products` takes the full name (`Nevada`) instead. */
            state: string | null;
            street: string | null;
        };
        /** @description Content capability — a media asset. */
        OctoMedia: {
            height: number | null;
            role: string;
            url: string;
            width: number | null;
        };
        OctoOption: {
            /**
             * @description Whether this option is currently live.
             *
             *     An active deal can still carry inactive options, so check this before
             *     offering one. `null` means Groupon does not know -- treat it as unknown, not
             *     as inactive. To list only live options, filter on `active !== false`.
             *
             *     A Groupon extension -- not part of the standard OCTO contract.
             */
            active: boolean | null;
            /** @description Always empty today, for EVERY product regardless of `availabilityType` — start times arrive with the availability endpoints, which are out of scope. A START_TIME product does not carry them here either. */
            availabilityLocalStartTimes: string[];
            cancellationCutoff: string;
            cancellationCutoffAmount: number;
            cancellationCutoffUnit: components["schemas"]["OctoDurationUnit"];
            default: boolean;
            id: string;
            internalName: string;
            reference: string | null;
            requiredContactFields: components["schemas"]["OctoContactField"][];
            restrictions: components["schemas"]["OctoOptionRestrictions"];
            /** @description Groupon extension. Always present — an empty array when the option carries no choose-one attribute, which is the majority case. */
            selections: components["schemas"]["OctoSelection"][];
            units: components["schemas"]["OctoUnit"][];
        };
        OctoOptionRestrictions: {
            maxUnits: number | null;
            minUnits: number;
        };
        OctoPricing: {
            currency: string;
            currencyPrecision: number;
            /**
             * @description The promotional price a shopper pays with an active Groupon promo code, plus the code and its expiry.
             *
             *     `null` when no promotion applies. Absent entirely on endpoints where a
             *     promotional price has no meaning -- only `GET /octo-gateway/v1/products` populates it.
             *
             *     A Groupon extension -- not part of the standard OCTO contract.
             */
            discountedPrice?: components["schemas"]["OctoDiscountedPrice"] | null;
            includedTaxes: components["schemas"]["OctoTax"][];
            net: number | null;
            original: number;
            retail: number;
        };
        OctoProduct: {
            allowFreesale: boolean;
            availabilityRequired: boolean;
            availabilityType: components["schemas"]["OctoAvailabilityType"];
            categoryLabels: string[];
            deliveryFormats: components["schemas"]["OctoDeliveryFormat"][];
            deliveryMethods: components["schemas"]["OctoDeliveryMethod"][];
            description: string;
            id: string;
            instantConfirmation: boolean;
            instantDelivery: boolean;
            internalName: string;
            locale: string;
            locations: components["schemas"]["OctoLocation"][];
            media: components["schemas"]["OctoMedia"][];
            options: components["schemas"]["OctoOption"][];
            redemptionMethod: components["schemas"]["OctoRedemptionMethod"];
            reference: string | null;
            shortDescription: string;
            /**
             * @description Whether this deal is on sale.
             *
             *     Separate from the `active` query parameter, which filters the page, and from
             *     an option's `available` flag, which is about bookable availability.
             */
            status: components["schemas"]["OctoProductStatus"];
            timeZone: string;
            /** @description Content capability (octo/content) */
            title: string;
        };
        /**
         * @description A deal's lifecycle state.
         *
         *     `active` is on sale, `sold_out` has no inventory left, and `expired` has
         *     ended. A Groupon extension, not part of the standard OCTO contract.
         * @enum {string}
         */
        OctoProductStatus: "active" | "sold_out" | "expired";
        /** @enum {string} */
        OctoRedemptionMethod: "DIGITAL" | "PRINT" | "MANIFEST";
        /**
         * @description A choice the shopper must make when booking, such as a pickup point or a service variant.
         *
         *     Exactly one value must be chosen. Echo `attributeId` and the chosen value's
         *     `id` back as `selections: [{ attributeId, valueId }]` when you request
         *     availability.
         *
         *     A Groupon extension, not part of the standard OCTO contract.
         */
        OctoSelection: {
            attributeId: string;
            /** @description Always true — a choose-one attribute has no "skip" value. */
            required: boolean;
            title: string;
            values: components["schemas"]["OctoSelectionValue"][];
        };
        /** @description One selectable value of a choose-one attribute, with the id echoed back verbatim in availability requests. */
        OctoSelectionValue: {
            id: string;
            title: string;
        };
        /** @description The supplier's contact block (all fields optional per OCTO). */
        OctoSupplierContact: {
            address: string | null;
            email: string | null;
            telephone: string | null;
            website: string | null;
        };
        /** @description Pricing capability — a single included-tax line. */
        OctoTax: {
            name: string;
            /** @description Groupon exposes no partner-net tax at this layer, so `net` is null (spec allows it). */
            net: number | null;
            original: number;
            retail: number;
        };
        OctoUnit: {
            id: string;
            internalName: string;
            /** @description Pricing capability. One row per unit (pricingPer = UNIT). */
            pricing: components["schemas"]["OctoPricing"][];
            reference: string | null;
            restrictions: components["schemas"]["OctoUnitRestrictions"];
            type: components["schemas"]["OctoUnitType"];
        };
        OctoUnitRestrictions: {
            maxQuantity: number | null;
            minQuantity: number | null;
        };
        /** @enum {string} */
        OctoUnitType: "ADULT" | "YOUTH" | "CHILD" | "INFANT" | "FAMILY" | "SENIOR" | "STUDENT" | "MILITARY" | "OTHER";
        /** @description One of your orders. On failure the error fields are set instead and every booking field is absent. */
        PartnerBookingGetResponse: {
            error?: components["schemas"]["OctoErrorCode"];
            errorMessage?: string;
            id?: string;
            items?: components["schemas"]["PartnerBookingItem"][];
            requestId?: string;
            status?: components["schemas"]["OctoBookingStatus"];
            supplierReference?: string | null;
            utcCreatedAt?: string;
            uuid?: string;
        };
        /** @description One line of an order: a product, the option bought, and its tickets. */
        PartnerBookingItem: {
            /** @description The option bought, as `options[].id` on `GET /products` and `optionId` on the cart item. */
            optionId: string;
            /** @description The product, as `id` on `GET /products` and as `productId` on the cart item you sent. Use it to join this line back to your catalog. `null` when the product is no longer in the catalog; `optionId` still identifies what was bought. */
            productId: string | null;
            /** @description How many of this option were bought. */
            quantity: number;
            /** @description This item's own state. It can differ from the order's: one item may be fully redeemed while another is still confirmed, or cancelled while another is not. `CANCELLED` once every ticket of the item is cancelled. */
            status: components["schemas"]["OctoBookingStatus"];
            /** @description One entry per ticket of this item. */
            unitItems: components["schemas"]["PartnerBookingUnitItem"][];
        };
        /** @description One reserved unit on an order -- a single ticket or voucher. */
        PartnerBookingUnitItem: {
            /**
             * @description A link to this unit on My Groupon, where the shopper views and redeems it.
             *
             *     Show it to the shopper after checkout; it is their voucher.
             */
            myGrouponUrl: string;
            /** @description This ticket's own state, which can differ from the order's -- one ticket may be redeemed or cancelled while others are not. */
            status: components["schemas"]["OctoBookingStatus"];
            /** @description This ticket's instance id — `order.items[].inventoryUnits[i].id`. */
            uuid: string;
        };
        /** @description Your partner registration. On failure the error fields are set instead and every registration field is absent. */
        PartnerMeGetResponse: {
            category0?: string[];
            category1?: string[];
            category2?: string[];
            cjPublisherId?: string | null;
            createdAt?: string;
            displayName?: string;
            error?: components["schemas"]["OctoErrorCode"];
            errorMessage?: string;
            inventoryCountries?: string[];
            inventoryStates?: string[];
            logoUrl?: string | null;
            maxPageSize?: number | null;
            partnerContactEmail?: string;
            partnerContactName?: string;
            partnerId?: string;
            redirectUrl?: string | null;
            requestId?: string;
            status?: components["schemas"]["PartnerStatus"];
            updatedAt?: string;
        };
        /** @description Your partner registration and API key. On failure the error fields are set instead and both are absent. */
        PartnerRegisterResponse: {
            error?: components["schemas"]["OctoErrorCode"];
            errorMessage?: string;
            partner?: components["schemas"]["PartnerRegistrationView"];
            requestId?: string;
            token?: string;
        };
        /** @description A partner registration to create. */
        PartnerRegistrationInput: {
            /** @description Category permalinks you will sell at depth 0 (e.g. `local`). Omit or send `[]` for no restriction. */
            category0?: string[];
            /** @description Category permalinks you will sell at depth 1 (e.g. `things-to-do`). Omit or send `[]` for no restriction. */
            category1?: string[];
            /** @description Category permalinks you will sell at depth 2. Omit or send `[]` for no restriction. */
            category2?: string[];
            /** @description Your Commission Junction publisher id, if you have one. With it, cart `buyLink`s are CJ affiliate links; omit it (or send `null` or blank) and `buyLink` is the direct Groupon checkout page. */
            cjPublisherId?: string | null;
            /** @description Shown to shoppers on Groupon's checkout. At most 60 characters, Latin letters only. It must not contain "Groupon", a web address, an email address, a phone number, or invisible characters. A name that breaks a rule is rejected with `BAD_REQUEST` naming the rule, and the call counts toward the rate limit. */
            displayName: string;
            /** @description Countries you will sell, ISO-3166 alpha-2. Only `US` is available today; omit it for `["US"]`. */
            inventoryCountries?: string[];
            /** @description US states you will sell, by full name. Omit or send `[]` for no state restriction. */
            inventoryStates?: string[];
            /** @description Logo shown on Groupon's cobranded checkout. Must be an `https://` URL. Omit it and your shoppers check out on the standard Groupon page. */
            logoUrl?: string;
            /** @description Your ceiling on `GET /products?limit=`, a positive integer. Omit for the service default. */
            maxPageSize?: number;
            /** @description Where Groupon contacts you. */
            partnerContactEmail: string;
            /** @description The person Groupon contacts about this integration. */
            partnerContactName: string;
            /** @description Where Groupon's checkout sends the shopper back to after payment. Must be an `https://` URL. */
            redirectUrl?: string;
        };
        /** @description A partner registration. Never includes the API key. */
        PartnerRegistrationView: {
            /** @description Category permalinks you may sell at depth 0 (e.g. `local`). Empty = no restriction. */
            category0: string[];
            /** @description Category permalinks you may sell at depth 1 (e.g. `things-to-do`). Empty = no restriction. */
            category1: string[];
            /** @description Category permalinks you may sell at depth 2. Empty = no restriction. */
            category2: string[];
            /** @description `null` = no CJ publisher id: cart `buyLink` is the direct Groupon checkout page. */
            cjPublisherId: string | null;
            createdAt: string;
            /** @description INTERNAL: portal only; GET /octo-gateway/v1/partners/me omits both (they can hold employee user ids). */
            createdBy: string;
            /** @description Shown to shoppers on Groupon's checkout. */
            displayName: string;
            /** @description Countries you may sell, ISO-3166 alpha-2. */
            inventoryCountries: string[];
            /** @description US states you may sell, by full name (`Pennsylvania`, not `PA`). Empty = no state restriction. */
            inventoryStates: string[];
            /** @description Logo shown on Groupon's cobranded checkout; `null` = no logo, and your shoppers check out on the standard Groupon page instead. */
            logoUrl: string | null;
            /** @description Your ceiling on `GET /products?limit=`; `null` = the service default. */
            maxPageSize: number | null;
            partnerContactEmail: string;
            partnerContactName: string;
            /** @description Your partner id: stable for the life of the registration, and the id Groupon attributes your orders to. */
            partnerId: string;
            /** @description Where Groupon's checkout sends the shopper back to after payment; `null` = no link. */
            redirectUrl: string | null;
            status: components["schemas"]["PartnerStatus"];
            updatedAt: string;
            updatedBy: string;
        };
        /**
         * @description `active`, or `deactivated` once the partner is switched off.
         * @enum {string}
         */
        PartnerStatus: "active" | "deactivated";
        /** @description A page of products. On failure the error fields are set instead and every product field is absent. */
        ProductsListResponse: {
            error?: components["schemas"]["OctoErrorCode"];
            errorMessage?: string;
            hasMore?: boolean;
            nextCursor?: string | null;
            products?: components["schemas"]["OctoProduct"][];
            requestId?: string;
            timestamp?: string;
        };
        /** @description Your supplier record. On failure the error fields are set instead and every supplier field is absent. */
        SupplierGetResponse: {
            contact?: components["schemas"]["OctoSupplierContact"];
            endpoint?: string;
            error?: components["schemas"]["OctoErrorCode"];
            errorMessage?: string;
            id?: string;
            name?: string;
            requestId?: string;
        };
        /** @description Change the quantity of one line in a cart. A quantity of 0 is rejected; to remove the line, delete it instead. */
        UpdateCartItemRequest: {
            /** @description ISO-3166 alpha-2 country code. Use `US` -- the only market available today. */
            country?: string;
            /** @description The per-unit price your site is showing, in minor units. When it disagrees with Groupon's live price the call fails with `PRICE_MISMATCH` and reports the current price, so the shopper never sees one price on your site and another at checkout. Optional, but strongly recommended. */
            expectedPrice?: number;
            quantity: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cartsCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCartRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoCart"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The HTTP status reflects `code`; the endpoint's own error is in `details`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoErrorEnvelope"];
                };
            };
        };
    };
    cartsGet: {
        parameters: {
            query?: {
                /** @description ISO-3166 alpha-2 country code. Use `US` -- the only market available today. */
                country?: string;
            };
            header?: never;
            path: {
                cartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoCart"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The HTTP status reflects `code`; the endpoint's own error is in `details`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoErrorEnvelope"];
                };
            };
        };
    };
    cartsAbandon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The HTTP status reflects `code`; the endpoint's own error is in `details`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoErrorEnvelope"];
                };
            };
        };
    };
    cartItemsAdd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartItemsRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoCart"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The HTTP status reflects `code`; the endpoint's own error is in `details`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoErrorEnvelope"];
                };
            };
        };
    };
    cartItemsRemove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoCart"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The HTTP status reflects `code`; the endpoint's own error is in `details`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoErrorEnvelope"];
                };
            };
        };
    };
    cartItemsUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartItemRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoCart"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The HTTP status reflects `code`; the endpoint's own error is in `details`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoErrorEnvelope"];
                };
            };
        };
    };
    partnerBookingGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerBookingGetResponse"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The body is the error object itself; the HTTP status reflects `error`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoError"];
                };
            };
        };
    };
    partnerMeGet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerMeGetResponse"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The body is the error object itself; the HTTP status reflects `error`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoError"];
                };
            };
        };
    };
    productsList: {
        parameters: {
            query: {
                /**
                 * @description ISO-3166 alpha-2 country code. Use `US` -- the only market available today.
                 *
                 *     A Groupon extension; required.
                 */
                country: string;
                /**
                 * @description Products per page. Defaults to 100; **10 is recommended**. A large page (500 and up) can exceed the request time budget and fail, so walk the catalogue with `limit=10`. Your account may have a lower cap, and a larger value is silently reduced to it rather than rejected.
                 *
                 *     A Groupon extension.
                 */
                limit?: number;
                /**
                 * @description The `nextCursor` from the previous page. Omit on the first page.
                 *
                 *     Treat the value as opaque and send it back exactly as received, keeping
                 *     every other query parameter identical across one walk.
                 *
                 *     A Groupon extension.
                 */
                cursor?: string;
                /**
                 * @description US state matched against the deal's divisions (Groupon extension).
                 *
                 *     Send the FULL STATE NAME exactly as stored, e.g. `Pennsylvania`,
                 *     `California`, `New York` — NOT an abbreviation such as `PA`, and not
                 *     `PENNSYLVANIA`. The match is case-SENSITIVE: only surrounding whitespace is
                 *     trimmed, and the value is otherwise passed through verbatim, so a
                 *     differently-cased or abbreviated value returns an EMPTY page rather than an
                 *     error. Omit to apply no state filter.
                 *
                 *     Locations on the response report `state` as a two-letter code (`PA`); this
                 *     filter still takes the full name.
                 */
                state?: string;
                /** @description Top-level category permalink: `local`, `goods` or `travel`. A Groupon extension. Each `category1` value belongs to exactly one of these. */
                category0?: string;
                /**
                 * @description Category permalink one level below `category0`. A Groupon extension. Send it alone, or together with its own `category0`; a pair from different parents returns no products. Values, by parent:
                 *
                 *     - `local`: `beauty-and-spas`, `health-and-fitness`, `things-to-do`,
                 *     `personal-services`, `food-and-drink`, `automotive`, `home-improvement`,
                 *     `retail`, `gift-cards`.
                 *     - `goods`: `v1-personalized-items`, `sports-and-outdoors`, `electronics`,
                 *     `grocery-and-household`, `for-the-home`, `baby-kids-and-toys`,
                 *     `health-and-beauty`, `entertainment-and-media`, `jewelry-and-watches`,
                 *     `pet-supplies`, `mens-clothing-shoes-and-accessories`,
                 *     `auto-and-home-improvement`.
                 *     - `travel`: `air-inclusive`, `city`, `family-trips`,
                 *     `outdoor-activities-recreation`, `beach-destinations`, `all-inclusive`,
                 *     `hotel-travel`, `unique-lodging`, `cruises`, `waterparks`,
                 *     `spa-and-wellness`.
                 */
                category1?: string;
                /** @description Category permalink at depth 2. A Groupon extension. */
                category2?: string;
                /** @description Category permalink at depth 3. A Groupon extension. */
                category3?: string;
                /**
                 * @description Whether to filter on the deal's active flag (Groupon extension). When OMITTED no filter is applied at all and the page carries both active and inactive deals — read each product's `status` to tell them apart.
                 *
                 *     Distinct from `status` (the deal's lifecycle state on the response) and from
                 *     an option's `available` flag (bookable availability).
                 */
                active?: boolean;
                /**
                 * @description ISO-8601 freshness watermark (Groupon extension). Returns only deals whose price or content changed at or after this instant. Omit to return all deals.
                 *
                 *     Use the `timestamp` from the final page of your previous walk; it already
                 *     allows for clock skew and for deals updated while that walk was running.
                 *
                 *     When a Groupon-wide promotion has started since this instant, prices can
                 *     change on deals whose own update time did not move, so the filter is
                 *     dropped for the whole walk and every deal is returned. That decision is
                 *     made on the first page and carried in the cursor, so a walk is never partly
                 *     incremental. Treat every page as authoritative and upsert what you receive.
                 */
                updatedSince?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductsListResponse"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The body is the error object itself; the HTTP status reflects `error`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoError"];
                };
            };
        };
    };
    partnerRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartnerRegistrationInput"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerRegisterResponse"];
                };
            };
            /** @description Error. The body is the error object itself; the HTTP status reflects `error`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoError"];
                };
            };
        };
    };
    supplierGet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierGetResponse"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The body is the error object itself; the HTTP status reflects `error`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoError"];
                };
            };
        };
    };
    cartsCreateLegacyPath: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCartRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoCart"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The HTTP status reflects `code`; the endpoint's own error is in `details`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoErrorEnvelope"];
                };
            };
        };
    };
    cartsGetLegacyPath: {
        parameters: {
            query?: {
                /** @description ISO-3166 alpha-2 country code. Use `US` -- the only market available today. */
                country?: string;
            };
            header?: never;
            path: {
                cartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoCart"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The HTTP status reflects `code`; the endpoint's own error is in `details`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoErrorEnvelope"];
                };
            };
        };
    };
    cartsAbandonLegacyPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The HTTP status reflects `code`; the endpoint's own error is in `details`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoErrorEnvelope"];
                };
            };
        };
    };
    cartItemsAddLegacyPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartItemsRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoCart"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The HTTP status reflects `code`; the endpoint's own error is in `details`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoErrorEnvelope"];
                };
            };
        };
    };
    cartItemsRemoveLegacyPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoCart"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The HTTP status reflects `code`; the endpoint's own error is in `details`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoErrorEnvelope"];
                };
            };
        };
    };
    cartItemsUpdateLegacyPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartItemRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoCart"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The HTTP status reflects `code`; the endpoint's own error is in `details`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoErrorEnvelope"];
                };
            };
        };
    };
    partnerBookingGetLegacyPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerBookingGetResponse"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The body is the error object itself; the HTTP status reflects `error`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoError"];
                };
            };
        };
    };
    productsListLegacyPath: {
        parameters: {
            query: {
                /**
                 * @description ISO-3166 alpha-2 country code. Use `US` -- the only market available today.
                 *
                 *     A Groupon extension; required.
                 */
                country: string;
                /**
                 * @description Products per page. Defaults to 100; **10 is recommended**. A large page (500 and up) can exceed the request time budget and fail, so walk the catalogue with `limit=10`. Your account may have a lower cap, and a larger value is silently reduced to it rather than rejected.
                 *
                 *     A Groupon extension.
                 */
                limit?: number;
                /**
                 * @description The `nextCursor` from the previous page. Omit on the first page.
                 *
                 *     Treat the value as opaque and send it back exactly as received, keeping
                 *     every other query parameter identical across one walk.
                 *
                 *     A Groupon extension.
                 */
                cursor?: string;
                /**
                 * @description US state matched against the deal's divisions (Groupon extension).
                 *
                 *     Send the FULL STATE NAME exactly as stored, e.g. `Pennsylvania`,
                 *     `California`, `New York` — NOT an abbreviation such as `PA`, and not
                 *     `PENNSYLVANIA`. The match is case-SENSITIVE: only surrounding whitespace is
                 *     trimmed, and the value is otherwise passed through verbatim, so a
                 *     differently-cased or abbreviated value returns an EMPTY page rather than an
                 *     error. Omit to apply no state filter.
                 *
                 *     Locations on the response report `state` as a two-letter code (`PA`); this
                 *     filter still takes the full name.
                 */
                state?: string;
                /** @description Top-level category permalink: `local`, `goods` or `travel`. A Groupon extension. Each `category1` value belongs to exactly one of these. */
                category0?: string;
                /**
                 * @description Category permalink one level below `category0`. A Groupon extension. Send it alone, or together with its own `category0`; a pair from different parents returns no products. Values, by parent:
                 *
                 *     - `local`: `beauty-and-spas`, `health-and-fitness`, `things-to-do`,
                 *     `personal-services`, `food-and-drink`, `automotive`, `home-improvement`,
                 *     `retail`, `gift-cards`.
                 *     - `goods`: `v1-personalized-items`, `sports-and-outdoors`, `electronics`,
                 *     `grocery-and-household`, `for-the-home`, `baby-kids-and-toys`,
                 *     `health-and-beauty`, `entertainment-and-media`, `jewelry-and-watches`,
                 *     `pet-supplies`, `mens-clothing-shoes-and-accessories`,
                 *     `auto-and-home-improvement`.
                 *     - `travel`: `air-inclusive`, `city`, `family-trips`,
                 *     `outdoor-activities-recreation`, `beach-destinations`, `all-inclusive`,
                 *     `hotel-travel`, `unique-lodging`, `cruises`, `waterparks`,
                 *     `spa-and-wellness`.
                 */
                category1?: string;
                /** @description Category permalink at depth 2. A Groupon extension. */
                category2?: string;
                /** @description Category permalink at depth 3. A Groupon extension. */
                category3?: string;
                /**
                 * @description Whether to filter on the deal's active flag (Groupon extension). When OMITTED no filter is applied at all and the page carries both active and inactive deals — read each product's `status` to tell them apart.
                 *
                 *     Distinct from `status` (the deal's lifecycle state on the response) and from
                 *     an option's `available` flag (bookable availability).
                 */
                active?: boolean;
                /**
                 * @description ISO-8601 freshness watermark (Groupon extension). Returns only deals whose price or content changed at or after this instant. Omit to return all deals.
                 *
                 *     Use the `timestamp` from the final page of your previous walk; it already
                 *     allows for clock skew and for deals updated while that walk was running.
                 *
                 *     When a Groupon-wide promotion has started since this instant, prices can
                 *     change on deals whose own update time did not move, so the filter is
                 *     dropped for the whole walk and every deal is returned. That decision is
                 *     made on the first page and carried in the cursor, so a walk is never partly
                 *     incremental. Treat every page as authoritative and upsert what you receive.
                 */
                updatedSince?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductsListResponse"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The body is the error object itself; the HTTP status reflects `error`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoError"];
                };
            };
        };
    };
    supplierGetLegacyPath: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierGetResponse"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Error. The body is the error object itself; the HTTP status reflects `error`. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OctoError"];
                };
            };
        };
    };
}
